[project]
name = "tokenization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.5",
    "nltk>=3.9.2",
    "openai>=2.17.0",
    "pydantic>=2.12.5",
]
